name: echo_era
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.3.1
  video_player: ^2.8.2
  shared_preferences: ^2.2.2
  audio_video_progress_bar: ^2.0.1
  go_router: ^13.0.1
  responsive_sizer: ^3.3.0+1
  flutter_downloader: ^1.11.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
